move_to_preset:
  description: Move the Vaddio Conferenceshot Camera to the specified preset
  fields:
    entity_id:
      description: Name(s) of entities to move to the specified preset.
      example: "camera.vaddio_conferenceshot_10"
      name: Entity
      required: true
      selector:
        entity:
          integration: vaddio_conferenceshot
          domain: camera
    preset:
      description: The integer number of any stored preset (1-16).
      example: 3
      name: Preset
      required: true
      selector:
        number:
          min: 1
          max: 16
          mode: box